services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      - meilisearch
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - HOST=0.0.0.0
      - JWT_SECRET=b5282930799c56f6c2618bfa32aee4f73783973a806961dab1c8495c472435c1
      - CREDS_KEY=e5ddc02d7566d2e3e31fce20ac209f3c848c5e12404eccf01a5c8cb8c89d8a7e
      - CREDS_IV=bc1c3fca6ba719772a74603a7c625489
      - NEXTAUTH_SECRET=b5282930799c56f6c2618bfa32aee4f73783973a806961dab1c8495c472435c1
      - SESSION_SECRET=b5282930799c56f6c2618bfa32aee4f73783973a806961dab1c8495c472435c1
      - OPENAI_API_KEY=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
      - ENDPOINTS=openAI
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ./assets/logo.png:/app/client/dist/assets/logo.png:ro

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.2
    restart: always

networks:
  default:
    name: librechat_default
